# Generated by Django 5.1 on 2024-08-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="product_name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="sku",
            new_name="serial_number",
        ),
    ]
