# Generated by Django 5.1 on 2024-08-15 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0002_rename_name_product_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivered_date",
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="invApp/products/"
            ),
        ),
    ]
