# Generated by Django 5.1 on 2024-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0003_product_delivered_date_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="delivered_date",
            field=models.DateField(),
        ),
    ]
