# Generated by Django 5.1 on 2024-08-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0004_alter_product_delivered_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="delivered_date",
            field=models.DateTimeField(),
        ),
    ]
