# Generated by Django 5.1 on 2024-08-15 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0005_alter_product_delivered_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="delivered_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 15, 23, 42, 45, 728222)
            ),
        ),
    ]
