# Generated by Django 5.1 on 2024-08-15 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0006_alter_product_delivered_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="delivered_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 16, 0, 6, 18, 449640)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                default="defaults/default.png", upload_to="invApp/products/"
            ),
        ),
    ]
